### ISSUE TITLE
ociextirpater gives 401 while OCI CLI working fine

### ISSUE THREAD

**Issue by Chandrak1907** [therealcmj/ociextirpater#11]
I could run oci cli commands to see the sub-compartments. However, I get 401 error with extirpator

```

ociextirpater % oci --profile INTEGRATION03 iam compartment list  --compartment-id ocid1.compartment.oc1..aaaaaaaans2yiucic5vvkao7ynID
{
  "data": [
    {
      "compartment-id": "ocid1.compartment.oc1..aaaaaaaans2yiucic5vvkao7ynujzyID",
      "defined-tags": {
        "DevRel\\redbull-analytics-hol-5ed0": {
          "release": "1.0"
        },

```
Could you please how to resolve this?

**Comment by therealcmj** [comment]
I see you're using the "--profile" argument on the OCI CLI. You may have missed doing the same with the extirpater. Try

`./ociextirpate.py -c ocid1.compartment.oc1..aaaaaaaans2yiucic5vvkao7ynID -cp INTEGRATION03`

**Comment by Chandrak1907** [comment]
Thank you.
