### ISSUE TITLE
script doesn't work in Cloud Shell

### ISSUE THREAD

**Issue by therealcmj** [therealcmj/ociextirpater#3]
the code for "-dt" was lifted from elsewhere and doesn't work. Need to fix.

**Comment by wanax1** [comment]
Hi Christopher,

The tool is great.
Might I know if the script works well in Cloud Shell now?
I just tried the script in Cloud Shell, got the following error.

2024-05-22 14:09:42,209 MainThread    INFO OCIClient:__init__ -> Initializing clients...
Traceback (most recent call last):
  File "ociextirpate.py", line 35, in <module>
    o = cls( cfg )
  File "/home/admin/ociextirpater/ociextirpater/OCIClient.py", line 37, in __init__
    self._init_regional_client(config.ociconfig, config.home_region)
  File "/home/admin/ociextirpater/ociextirpater/OCIClient.py", line 18, in _init_regional_client
    logging.debug("Old region in this OCI config dict: {}".format(rconfig["region"]))
KeyError: 'region'
admin@cloudshell:ociextirpater (ap-tokyo-1)$

**Comment by therealcmj** [comment]
After a few hiccups I am actually planning to look into that today or tomorrow and should be able to get it working.

**Comment by therealcmj** [comment]
Fixed in bffaa27

to use the script in Cloud Shell add the -dt command line option. I will be making other improvements to autodetect cloud shell later but this is the initial fix

**Comment by therealcmj** [comment]
Fixed in bffaa27
