### ISSUE TITLE
Multi-Compartment Single Code Execution

### ISSUE THREAD

**Issue by jake-oci** [therealcmj/ociextirpater#8]
Example: ociextirpater.py -c compartment1, compartment2, compartment3.

Sometimes I want to nuke multiple compartments and don't want to run the code several times to accomplish that. I'm thinking argparse taking in a list will accomplish the compartment intake, and threading execute the multiple iterations of this function.

Thank you!

**Comment by therealcmj** [comment]
Unfortunately this would almost certainly run afoul of rate limits.

I have extended the script in commit c2332f8 to support multiple compartments. Just do -c ocid1.compartment.oc1...one -c ocid1.compartment.oc1...two -c ocid1.compartment.oc1...three
